// SPDX-License-Identifier: MPL-2.0
// Copyright © 2026 Lee Kelleher

// Hand-rolled Service classes for the Contentment Management API.
//
// Previously generated by `@hey-api/openapi-ts`. The `class { static }` shape is preserved
// purely for back-compat with consumers of `@leekelleher/umbraco-contentment` who were
// importing the generated `*Service` classes. A from-scratch design would use free
// functions; the wrapper exists to avoid breaking external consumers.
//
// The `client` option is accepted on every method for back-compat (callers used to pass
// `umbHttpClient` here) but is ignored at runtime — `umbHttpClient` is always used.

import { umbHttpClient } from '@umbraco-cms/backoffice/http-client';

import type {
	GetAssembliesDataData,
	GetAssembliesDataError,
	GetAssembliesDataResponse,
	GetConfigurationData,
	GetConfigurationError,
	GetConfigurationResponse,
	GetDataPickerSearchData,
	GetDataPickerSearchError,
	GetDataPickerSearchResponse,
	GetElementTypesData,
	GetElementTypesError,
	GetElementTypesResponse,
	GetEnumsDataData,
	GetEnumsDataError,
	GetEnumsDataResponse,
	PostDataListEditorData,
	PostDataListEditorError,
	PostDataListEditorResponse,
	PostDataPickerEditorData,
	PostDataPickerEditorError,
	PostDataPickerEditorResponse,
	PostDataPickerSearchData,
	PostDataPickerSearchError,
	PostDataPickerSearchResponse,
} from './types.js';

/**
 * Options accepted by each service method. Mirrors the shape produced by the previous
 * `@hey-api/openapi-ts` generator so existing call sites and external consumers keep working.
 */
export type Options<TData = unknown, ThrowOnError extends boolean = boolean> = Partial<TData> & {
	client?: unknown;
	headers?: Record<string, string>;
	meta?: Record<string, unknown>;
	throwOnError?: ThrowOnError;
};

const bearerSecurity = [{ scheme: 'bearer', type: 'http' }] as const;

export class ContentBlocksService {
	public static getElementTypes<ThrowOnError extends boolean = true>(
		options?: Options<GetElementTypesData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetElementTypesResponse, GetElementTypesError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/content-blocks/element-types',
			headers: options?.headers,
		});
	}
}

export class DataListService {
	public static postDataListEditor<ThrowOnError extends boolean = true>(
		options?: Options<PostDataListEditorData, ThrowOnError>,
	) {
		return umbHttpClient.post<PostDataListEditorResponse, PostDataListEditorError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-list/editor',
			body: options?.body,
			headers: { 'Content-Type': 'application/json', ...options?.headers },
		});
	}

	/**
	 * Fetch items from an arbitrary URL — used by data sources that point at a custom server endpoint.
	 * The response shape is caller-determined; pass the expected item type as the generic parameter.
	 * Note: `security` is required, otherwise the request returns 401 unauthorized.
	 */
	public static getItemsByUrl<T = unknown>(url: string) {
		return umbHttpClient.get<Array<T>>({
			security: bearerSecurity,
			url,
		});
	}
}

export class DataPickerService {
	public static postDataPickerEditor<ThrowOnError extends boolean = true>(
		options?: Options<PostDataPickerEditorData, ThrowOnError>,
	) {
		return umbHttpClient.post<PostDataPickerEditorResponse, PostDataPickerEditorError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-picker/editor',
			body: options?.body,
			headers: { 'Content-Type': 'application/json', ...options?.headers },
		});
	}

	/** @deprecated */
	public static getDataPickerSearch<ThrowOnError extends boolean = true>(
		options?: Options<GetDataPickerSearchData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetDataPickerSearchResponse, GetDataPickerSearchError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-picker/search',
			query: options?.query,
			headers: options?.headers,
		});
	}

	public static postDataPickerSearch<ThrowOnError extends boolean = true>(
		options?: Options<PostDataPickerSearchData, ThrowOnError>,
	) {
		return umbHttpClient.post<PostDataPickerSearchResponse, PostDataPickerSearchError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-picker/search',
			body: options?.body,
			query: options?.query,
			headers: { 'Content-Type': 'application/json', ...options?.headers },
		});
	}
}

export class DataService {
	public static getAssembliesData<ThrowOnError extends boolean = true>(
		options?: Options<GetAssembliesDataData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetAssembliesDataResponse, GetAssembliesDataError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data/assemblies',
			headers: options?.headers,
		});
	}

	public static getEnumsData<ThrowOnError extends boolean = true>(options?: Options<GetEnumsDataData, ThrowOnError>) {
		return umbHttpClient.get<GetEnumsDataResponse, GetEnumsDataError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data/enums',
			query: options?.query,
			headers: options?.headers,
		});
	}
}

export class MetaService {
	public static getConfiguration<ThrowOnError extends boolean = true>(
		options?: Options<GetConfigurationData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetConfigurationResponse, GetConfigurationError, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/meta/configuration',
			headers: options?.headers,
		});
	}
}
