// SPDX-License-Identifier: MPL-2.0
// Copyright © 2026 Lee Kelleher

// Hand-rolled Service classes for the Contentment Management API.
//
// Previously generated by `@hey-api/openapi-ts`. The `class { static }` shape is preserved
// purely for back-compat with consumers of `@leekelleher/umbraco-contentment` who were
// importing the generated `*Service` classes. A from-scratch design would use free
// functions; the wrapper exists to avoid breaking external consumers.
//
// The `client` option is accepted on every method for back-compat (callers used to pass
// `umbHttpClient` here) but is ignored at runtime — `umbHttpClient` is always used.
//
// Note: `umbHttpClient.{get,post}` is generic over the full `*Responses` / `*Errors`
// records (e.g. `{ 200: DataListEditorResponseModel }`) and unwraps internally to expose
// the response value via `data`. Pass the `*Responses` shape, not the unwrapped value.

import { umbHttpClient } from '@umbraco-cms/backoffice/http-client';

import type {
	GetAssembliesDataData,
	GetAssembliesDataErrors,
	GetAssembliesDataResponses,
	GetConfigurationData,
	GetConfigurationErrors,
	GetConfigurationResponses,
	GetDataPickerSearchData,
	GetDataPickerSearchErrors,
	GetDataPickerSearchResponses,
	GetElementTypesData,
	GetElementTypesErrors,
	GetElementTypesResponses,
	GetEnumsDataData,
	GetEnumsDataErrors,
	GetEnumsDataResponses,
	PostDataListEditorData,
	PostDataListEditorErrors,
	PostDataListEditorResponses,
	PostDataPickerEditorData,
	PostDataPickerEditorErrors,
	PostDataPickerEditorResponses,
	PostDataPickerSearchData,
	PostDataPickerSearchErrors,
	PostDataPickerSearchResponses,
} from './types.js';

/**
 * Options accepted by each service method. Mirrors the shape produced by the previous
 * `@hey-api/openapi-ts` generator so existing call sites and external consumers keep working.
 */
export type Options<TData = unknown, ThrowOnError extends boolean = boolean> = Partial<TData> & {
	client?: unknown;
	headers?: Record<string, string>;
	meta?: Record<string, unknown>;
	throwOnError?: ThrowOnError;
};

const bearerSecurity = [{ scheme: 'bearer', type: 'http' }] as const;

export class ContentBlocksService {
	public static getElementTypes<ThrowOnError extends boolean = true>(
		options?: Options<GetElementTypesData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetElementTypesResponses, GetElementTypesErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/content-blocks/element-types',
			headers: options?.headers,
		});
	}
}

export class DataListService {
	public static postDataListEditor<ThrowOnError extends boolean = true>(
		options?: Options<PostDataListEditorData, ThrowOnError>,
	) {
		return umbHttpClient.post<PostDataListEditorResponses, PostDataListEditorErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-list/editor',
			body: options?.body,
			headers: { 'Content-Type': 'application/json', ...options?.headers },
		});
	}
}

export class DataPickerService {
	public static postDataPickerEditor<ThrowOnError extends boolean = true>(
		options?: Options<PostDataPickerEditorData, ThrowOnError>,
	) {
		return umbHttpClient.post<PostDataPickerEditorResponses, PostDataPickerEditorErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-picker/editor',
			body: options?.body,
			headers: { 'Content-Type': 'application/json', ...options?.headers },
		});
	}

	/** @deprecated */
	public static getDataPickerSearch<ThrowOnError extends boolean = true>(
		options?: Options<GetDataPickerSearchData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetDataPickerSearchResponses, GetDataPickerSearchErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-picker/search',
			query: options?.query,
			headers: options?.headers,
		});
	}

	public static postDataPickerSearch<ThrowOnError extends boolean = true>(
		options?: Options<PostDataPickerSearchData, ThrowOnError>,
	) {
		return umbHttpClient.post<PostDataPickerSearchResponses, PostDataPickerSearchErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data-picker/search',
			body: options?.body,
			query: options?.query,
			headers: { 'Content-Type': 'application/json', ...options?.headers },
		});
	}
}

export class DataService {
	public static getAssembliesData<ThrowOnError extends boolean = true>(
		options?: Options<GetAssembliesDataData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetAssembliesDataResponses, GetAssembliesDataErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data/assemblies',
			headers: options?.headers,
		});
	}

	public static getEnumsData<ThrowOnError extends boolean = true>(
		options?: Options<GetEnumsDataData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetEnumsDataResponses, GetEnumsDataErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/data/enums',
			query: options?.query,
			headers: options?.headers,
		});
	}
}

export class MetaService {
	public static getConfiguration<ThrowOnError extends boolean = true>(
		options?: Options<GetConfigurationData, ThrowOnError>,
	) {
		return umbHttpClient.get<GetConfigurationResponses, GetConfigurationErrors, ThrowOnError>({
			security: bearerSecurity,
			url: '/umbraco/management/api/v1/contentment/meta/configuration',
			headers: options?.headers,
		});
	}
}
