// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModelEnum {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export enum OverlaySizeEnum {
    SMALL = 'Small',
    MEDIUM = 'Medium',
    LARGE = 'Large'
}