// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetAssembliesDataResponse, GetEnumsDataData, GetEnumsDataResponse, PostDataListEditorData, PostDataListEditorResponse, PostDataPickerEditorData, PostDataPickerEditorResponse, GetDataPickerSearchData, GetDataPickerSearchResponse } from './types.gen';

export class DataService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getAssembliesData(): CancelablePromise<GetAssembliesDataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/data/assemblies',
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.assembly
     * @returns unknown OK
     * @throws ApiError
     */
    public static getEnumsData(data: GetEnumsDataData = {}): CancelablePromise<GetEnumsDataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/data/enums',
            query: {
                assembly: data.assembly
            },
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}

export class DataListService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postDataListEditor(data: PostDataListEditorData = {}): CancelablePromise<PostDataListEditorResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/v1/contentment/data-list/editor',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}

export class DataPickerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postDataPickerEditor(data: PostDataPickerEditorData = {}): CancelablePromise<PostDataPickerEditorResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/v1/contentment/data-picker/editor',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @param data.dataTypeKey
     * @param data.pageNumber
     * @param data.pageSize
     * @param data.query
     * @param data.alias
     * @param data.variant
     * @returns unknown OK
     * @throws ApiError
     */
    public static getDataPickerSearch(data: GetDataPickerSearchData = {}): CancelablePromise<GetDataPickerSearchResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/data-picker/search',
            query: {
                id: data.id,
                dataTypeKey: data.dataTypeKey,
                pageNumber: data.pageNumber,
                pageSize: data.pageSize,
                query: data.query,
                alias: data.alias,
                variant: data.variant
            },
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}