// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
	GetAssembliesDataData,
	GetAssembliesDataErrors,
	GetAssembliesDataResponses,
	GetConfigurationData,
	GetConfigurationErrors,
	GetConfigurationResponses,
	GetDataPickerSearchData,
	GetDataPickerSearchErrors,
	GetDataPickerSearchResponses,
	GetElementTypesData,
	GetElementTypesErrors,
	GetElementTypesResponses,
	GetEnumsDataData,
	GetEnumsDataErrors,
	GetEnumsDataResponses,
	PostDataListEditorData,
	PostDataListEditorErrors,
	PostDataListEditorResponses,
	PostDataPickerEditorData,
	PostDataPickerEditorErrors,
	PostDataPickerEditorResponses,
	PostDataPickerSearchData,
	PostDataPickerSearchErrors,
	PostDataPickerSearchResponses,
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export class ContentBlocksService {
	public static getElementTypes<ThrowOnError extends boolean = true>(
		options?: Options<GetElementTypesData, ThrowOnError>,
	) {
		return (options?.client ?? client).get<GetElementTypesResponses, GetElementTypesErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/content-blocks/element-types',
			...options,
		});
	}
}

export class DataService {
	public static getAssembliesData<ThrowOnError extends boolean = true>(
		options?: Options<GetAssembliesDataData, ThrowOnError>,
	) {
		return (options?.client ?? client).get<GetAssembliesDataResponses, GetAssembliesDataErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/data/assemblies',
			...options,
		});
	}

	public static getEnumsData<ThrowOnError extends boolean = true>(options?: Options<GetEnumsDataData, ThrowOnError>) {
		return (options?.client ?? client).get<GetEnumsDataResponses, GetEnumsDataErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/data/enums',
			...options,
		});
	}
}

export class DataListService {
	public static postDataListEditor<ThrowOnError extends boolean = true>(
		options: Options<PostDataListEditorData, ThrowOnError>,
	) {
		return (options.client ?? client).post<PostDataListEditorResponses, PostDataListEditorErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/data-list/editor',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		});
	}
}

export class DataPickerService {
	public static postDataPickerEditor<ThrowOnError extends boolean = true>(
		options: Options<PostDataPickerEditorData, ThrowOnError>,
	) {
		return (options.client ?? client).post<PostDataPickerEditorResponses, PostDataPickerEditorErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/data-picker/editor',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		});
	}

	public static getDataPickerSearch<ThrowOnError extends boolean = true>(
		options?: Options<GetDataPickerSearchData, ThrowOnError>,
	) {
		return (options?.client ?? client).get<GetDataPickerSearchResponses, GetDataPickerSearchErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/data-picker/search',
			...options,
		});
	}

	public static postDataPickerSearch<ThrowOnError extends boolean = true>(
		options?: Options<PostDataPickerSearchData, ThrowOnError>,
	) {
		return (options?.client ?? client).post<PostDataPickerSearchResponses, PostDataPickerSearchErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/data-picker/search',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options?.headers,
			},
		});
	}
}

export class MetaService {
	public static getConfiguration<ThrowOnError extends boolean = true>(
		options?: Options<GetConfigurationData, ThrowOnError>,
	) {
		return (options?.client ?? client).get<GetConfigurationResponses, GetConfigurationErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/management/api/v1/contentment/meta/configuration',
			...options,
		});
	}
}
