// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class ConfigurationEditorService {
    /**
     * @param data The data for the request.
     * @param data.type
     * @returns unknown OK
     * @throws ApiError
     */
    public static getConfigurationEditorEditorModels(data: $OpenApiTs['/umbraco/management/api/v1/contentment/configuration-editor/models']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/contentment/configuration-editor/models']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/configuration-editor/models',
            query: {
                type: data.type
            },
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}

export class DataListService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postDataListEditor(data: $OpenApiTs['/umbraco/management/api/v1/contentment/data-list/editor']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/contentment/data-list/editor']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/v1/contentment/data-list/editor',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}

export class DataPickerService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postDataPickerEditor(data: $OpenApiTs['/umbraco/management/api/v1/contentment/data-picker/editor']['post']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/contentment/data-picker/editor']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/v1/contentment/data-picker/editor',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @param data.dataTypeKey
     * @param data.pageNumber
     * @param data.pageSize
     * @param data.query
     * @returns unknown OK
     * @throws ApiError
     */
    public static getDataPickerSearch(data: $OpenApiTs['/umbraco/management/api/v1/contentment/data-picker/search']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/contentment/data-picker/search']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/data-picker/search',
            query: {
                id: data.id,
                dataTypeKey: data.dataTypeKey,
                pageNumber: data.pageNumber,
                pageSize: data.pageSize,
                query: data.query
            },
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}

export class DataService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getAssembliesData(): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/contentment/data/assemblies']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/data/assemblies',
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.assembly
     * @returns unknown OK
     * @throws ApiError
     */
    public static getEnumsData(data: $OpenApiTs['/umbraco/management/api/v1/contentment/data/enums']['get']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/contentment/data/enums']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/management/api/v1/contentment/data/enums',
            query: {
                assembly: data.assembly
            },
            errors: {
                401: 'The resource is protected and requires an authentication token',
                403: 'The authenticated user do not have access to this resource',
                404: 'Not Found'
            }
        });
    }
    
}