// This file is auto-generated by @hey-api/openapi-ts

export type ConfigurationEditorItemRequestModel = {
    key?: (string) | null;
    value?: {
        [key: string]: unknown;
    } | null;
};

export type ConfigurationEditorModel = {
    key: string;
    name: string;
    description?: (string) | null;
    icon?: (string) | null;
    group?: (string) | null;
    fields: Array<(ContentmentConfigurationFieldModel)>;
    defaultValues?: {
        [key: string]: unknown;
    } | null;
    overlaySize: OverlaySize;
    expressions?: {
        [key: string]: (string);
    } | null;
    /**
     * @deprecated
     */
    nameTemplate?: (string) | null;
    /**
     * @deprecated
     */
    descriptionTemplate?: (string) | null;
};

export type ConfigurationEditorModelsResponseModel = {
    items: Array<(ConfigurationEditorModel)>;
};

export type ContentmentConfigurationFieldModel = {
    key?: (string) | null;
    name?: (string) | null;
    description?: (string) | null;
    view?: (string) | null;
    propertyEditorUiAlias?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type DataListConfigurationRequestModel = {
    dataSource?: Array<(ConfigurationEditorItemRequestModel)> | null;
    listEditor?: Array<(ConfigurationEditorItemRequestModel)> | null;
};

export type DataListEditorResponseModel = {
    propertyEditorUiAlias?: (string) | null;
    config?: Array<(DataTypePropertyPresentationModel)> | null;
};

export type DataListItem = {
    description?: (string) | null;
    disabled: boolean;
    group?: (string) | null;
    icon?: (string) | null;
    name?: (string) | null;
    value?: (string) | null;
    [key: string]: (unknown | string | boolean) | undefined;
};

export type DataPickerEditorRequestModel = {
    id: string;
    dataTypeKey: string;
    dataSource?: Array<(ConfigurationEditorItemRequestModel)> | null;
    displayMode?: Array<(ConfigurationEditorItemRequestModel)> | null;
    values?: Array<(string)> | null;
};

export type DataPickerEditorResponseModel = {
    propertyEditorUiAlias?: (string) | null;
    config?: Array<(DataTypePropertyPresentationModel)> | null;
};

export type DataTypePropertyPresentationModel = {
    alias: string;
    value?: unknown;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export enum OverlaySize {
    SMALL = 'Small',
    MEDIUM = 'Medium',
    LARGE = 'Large'
}

export type PagedModelDataListItemModel = {
    items: Array<(DataListItem)>;
    total: number;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type GetConfigurationEditorEditorModelsData = {
    type?: string;
};

export type GetConfigurationEditorEditorModelsResponse = ((ConfigurationEditorModelsResponseModel));

export type GetAssembliesDataResponse = (Array<(DataListItem)>);

export type GetEnumsDataData = {
    assembly?: string;
};

export type GetEnumsDataResponse = (Array<(DataListItem)>);

export type PostDataListEditorData = {
    requestBody?: (DataListConfigurationRequestModel);
};

export type PostDataListEditorResponse = ((DataListEditorResponseModel));

export type PostDataPickerEditorData = {
    requestBody?: (DataPickerEditorRequestModel);
};

export type PostDataPickerEditorResponse = ((DataPickerEditorResponseModel));

export type GetDataPickerSearchData = {
    dataTypeKey?: string;
    id?: string;
    pageNumber?: number;
    pageSize?: number;
    query?: string;
};

export type GetDataPickerSearchResponse = ((PagedModelDataListItemModel));