// This file is auto-generated by @hey-api/openapi-ts

export type ConfigurationEditorItemRequestModel = {
    key?: (string) | null;
    value?: {
        [key: string]: unknown;
    } | null;
};

export type DataListConfigurationRequestModel = {
    alias?: (string) | null;
    dataSource?: ((ConfigurationEditorItemRequestModel) | null);
    id?: (string) | null;
    listEditor?: ((ConfigurationEditorItemRequestModel) | null);
    variant?: (string) | null;
};

export type DataListEditorResponseModel = {
    propertyEditorUiAlias?: (string) | null;
    config?: Array<(DataTypePropertyPresentationModel)> | null;
};

export type DataListItem = {
    description?: (string) | null;
    disabled: boolean;
    group?: (string) | null;
    icon?: (string) | null;
    name?: (string) | null;
    value?: (string) | null;
    [key: string]: (unknown | string | boolean) | undefined;
};

export type DataPickerEditorRequestModel = {
    alias?: (string) | null;
    dataSource?: ((ConfigurationEditorItemRequestModel) | null);
    dataTypeKey: string;
    displayMode?: ((ConfigurationEditorItemRequestModel) | null);
    id: string;
    values?: Array<(string)> | null;
    variant?: (string) | null;
};

export type DataPickerEditorResponseModel = {
    propertyEditorUiAlias?: (string) | null;
    config?: Array<(DataTypePropertyPresentationModel)> | null;
};

export type DataTypePropertyPresentationModel = {
    alias: string;
    value?: unknown;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedModelDataListItemModel = {
    items: Array<(DataListItem)>;
    total: number;
};

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type GetAssembliesDataResponse = (Array<(DataListItem)>);

export type GetEnumsDataData = {
    assembly?: string;
};

export type GetEnumsDataResponse = (Array<(DataListItem)>);

export type PostDataListEditorData = {
    requestBody?: (DataListConfigurationRequestModel);
};

export type PostDataListEditorResponse = ((DataListEditorResponseModel));

export type PostDataPickerEditorData = {
    requestBody?: (DataPickerEditorRequestModel);
};

export type PostDataPickerEditorResponse = ((DataPickerEditorResponseModel));

export type GetDataPickerSearchData = {
    alias?: string;
    dataTypeKey?: string;
    id?: string;
    pageNumber?: number;
    pageSize?: number;
    query?: string;
    variant?: string;
};

export type GetDataPickerSearchResponse = ((PagedModelDataListItemModel));