// SPDX-License-Identifier: MPL-2.0
// Copyright © 2026 Lee Kelleher

// Hand-rolled Contentment Management API types.
// Previously auto-generated by `@hey-api/openapi-ts`; now maintained by hand to drop the
// codegen dependency. Keep in sync with the C# request/response models when they change.

// ---------- Domain models ----------

export type ConfigurationEditorItemRequestModel = {
	key?: string | null;
	value?: {
		[key: string]: unknown;
	} | null;
};

export type ContentmentSettings = {
	disableTree: boolean;
	disableTelemetry: boolean;
};

export type DataListConfigurationRequestModel = {
	alias?: string | null;
	dataSource?: ConfigurationEditorItemRequestModel | null;
	id?: string | null;
	isNew?: boolean | null;
	parentId?: string | null;
	listEditor?: ConfigurationEditorItemRequestModel | null;
	variant?: string | null;
};

export type DataListEditorResponseModel = {
	propertyEditorUiAlias?: string | null;
	config?: Array<DataTypePropertyPresentationModel> | null;
};

export type DataListItem = {
	description?: string | null;
	disabled: boolean;
	group?: string | null;
	icon?: string | null;
	name?: string | null;
	value?: string | null;
	[key: string]: unknown;
};

export type DataPickerEditorRequestModel = {
	alias?: string | null;
	dataSource?: ConfigurationEditorItemRequestModel | null;
	dataTypeKey: string;
	displayMode?: ConfigurationEditorItemRequestModel | null;
	id: string;
	isNew?: boolean | null;
	parentId?: string | null;
	values?: Array<string> | null;
	variant?: string | null;
};

export type DataPickerEditorResponseModel = {
	propertyEditorUiAlias?: string | null;
	config?: Array<DataTypePropertyPresentationModel> | null;
};

export type DataTypePropertyPresentationModel = {
	alias: string;
	value?: unknown;
};

export enum EventMessageTypeModel {
	DEFAULT = 'Default',
	INFO = 'Info',
	ERROR = 'Error',
	SUCCESS = 'Success',
	WARNING = 'Warning',
}

export type MetaConfigurationResponseModel = {
	name?: string | null;
	version?: string | null;
	features?: ContentmentSettings | null;
};

export type NotificationHeaderModel = {
	message: string;
	category: string;
	type: EventMessageTypeModel;
};

export type PagedModelDataListItemModel = {
	items: Array<DataListItem>;
	total: number;
};

export type ProblemDetails = {
	type?: string | null;
	title?: string | null;
	status?: number | null;
	detail?: string | null;
	instance?: string | null;
	[key: string]: unknown;
};

// ---------- Client / runtime types ----------

export type ClientOptions = {
	baseUrl: string;
};

// ---------- Operation shapes ----------
// One trio per endpoint: `*Data` (input shape), `*Response[s]` (success), `*Error[s]` (failure).
// Re-exported through `index.ts` for back-compat with consumers of the previous generated SDK.

type ApiErrorStatuses = {
	/** The resource is protected and requires an authentication token */
	401: unknown;
	/** The authenticated user does not have access to this resource */
	403: unknown;
	/** Not Found */
	404: ProblemDetails;
};

// GET /content-blocks/element-types
export type GetElementTypesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/management/api/v1/contentment/content-blocks/element-types';
};
export type GetElementTypesErrors = ApiErrorStatuses;
export type GetElementTypesError = GetElementTypesErrors[keyof GetElementTypesErrors];
export type GetElementTypesResponses = { 200: Array<DataListItem> };
export type GetElementTypesResponse = GetElementTypesResponses[keyof GetElementTypesResponses];

// POST /data-list/editor
export type PostDataListEditorData = {
	body?: DataListConfigurationRequestModel;
	path?: never;
	query?: never;
	url: '/umbraco/management/api/v1/contentment/data-list/editor';
};
export type PostDataListEditorErrors = ApiErrorStatuses;
export type PostDataListEditorError = PostDataListEditorErrors[keyof PostDataListEditorErrors];
export type PostDataListEditorResponses = { 200: DataListEditorResponseModel };
export type PostDataListEditorResponse = PostDataListEditorResponses[keyof PostDataListEditorResponses];

// POST /data-picker/editor
export type PostDataPickerEditorData = {
	body?: DataPickerEditorRequestModel;
	path?: never;
	query?: never;
	url: '/umbraco/management/api/v1/contentment/data-picker/editor';
};
export type PostDataPickerEditorErrors = ApiErrorStatuses;
export type PostDataPickerEditorError = PostDataPickerEditorErrors[keyof PostDataPickerEditorErrors];
export type PostDataPickerEditorResponses = { 200: DataPickerEditorResponseModel };
export type PostDataPickerEditorResponse = PostDataPickerEditorResponses[keyof PostDataPickerEditorResponses];

// GET /data-picker/search (deprecated)
export type GetDataPickerSearchData = {
	body?: never;
	path?: never;
	query?: {
		id?: string;
		dataTypeKey?: string;
		pageNumber?: number;
		pageSize?: number;
		query?: string;
		alias?: string;
		variant?: string;
	};
	url: '/umbraco/management/api/v1/contentment/data-picker/search';
};
export type GetDataPickerSearchErrors = ApiErrorStatuses;
export type GetDataPickerSearchError = GetDataPickerSearchErrors[keyof GetDataPickerSearchErrors];
export type GetDataPickerSearchResponses = { 200: PagedModelDataListItemModel };
export type GetDataPickerSearchResponse = GetDataPickerSearchResponses[keyof GetDataPickerSearchResponses];

// POST /data-picker/search
export type PostDataPickerSearchData = {
	body?: Array<string>;
	path?: never;
	query?: {
		id?: string;
		dataTypeKey?: string;
		pageNumber?: number;
		pageSize?: number;
		query?: string;
		alias?: string;
		variant?: string;
		parentId?: string;
		isNew?: boolean;
	};
	url: '/umbraco/management/api/v1/contentment/data-picker/search';
};
export type PostDataPickerSearchErrors = ApiErrorStatuses;
export type PostDataPickerSearchError = PostDataPickerSearchErrors[keyof PostDataPickerSearchErrors];
export type PostDataPickerSearchResponses = { 200: PagedModelDataListItemModel };
export type PostDataPickerSearchResponse = PostDataPickerSearchResponses[keyof PostDataPickerSearchResponses];

// GET /data/assemblies
export type GetAssembliesDataData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/management/api/v1/contentment/data/assemblies';
};
export type GetAssembliesDataErrors = ApiErrorStatuses;
export type GetAssembliesDataError = GetAssembliesDataErrors[keyof GetAssembliesDataErrors];
export type GetAssembliesDataResponses = { 200: Array<DataListItem> };
export type GetAssembliesDataResponse = GetAssembliesDataResponses[keyof GetAssembliesDataResponses];

// GET /data/enums
export type GetEnumsDataData = {
	body?: never;
	path?: never;
	query?: { assembly?: string };
	url: '/umbraco/management/api/v1/contentment/data/enums';
};
export type GetEnumsDataErrors = ApiErrorStatuses;
export type GetEnumsDataError = GetEnumsDataErrors[keyof GetEnumsDataErrors];
export type GetEnumsDataResponses = { 200: Array<DataListItem> };
export type GetEnumsDataResponse = GetEnumsDataResponses[keyof GetEnumsDataResponses];

// GET /meta/configuration
export type GetConfigurationData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/management/api/v1/contentment/meta/configuration';
};
export type GetConfigurationErrors = ApiErrorStatuses;
export type GetConfigurationError = GetConfigurationErrors[keyof GetConfigurationErrors];
export type GetConfigurationResponses = { 200: MetaConfigurationResponseModel };
export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];
