//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.17.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "componentCodeRenderPositionProperty"
	/// <summary>[Component] Code Render Position Property</summary>
	public partial interface IComponentCodeRenderPositionProperty : IPublishedElement
	{
		/// <summary>Render Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		global::Umbraco.Web.PublishedModels.RenderPosition RenderPosition { get; }
	}

	/// <summary>[Component] Code Render Position Property</summary>
	[PublishedModel("componentCodeRenderPositionProperty")]
	public partial class ComponentCodeRenderPositionProperty : PublishedElementModel, IComponentCodeRenderPositionProperty
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public new const string ModelTypeAlias = "componentCodeRenderPositionProperty";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ComponentCodeRenderPositionProperty, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ComponentCodeRenderPositionProperty(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Render Position: Select the position to render the code snippet. The default position is "Before the closing &lt;/body&gt; tag".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		[ImplementPropertyType("renderPosition")]
		public virtual global::Umbraco.Web.PublishedModels.RenderPosition RenderPosition => GetRenderPosition(this);

		/// <summary>Static getter for Render Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public static global::Umbraco.Web.PublishedModels.RenderPosition GetRenderPosition(IComponentCodeRenderPositionProperty that) => that.Value<global::Umbraco.Web.PublishedModels.RenderPosition>("renderPosition");
	}
}
