// This file is auto-generated by @hey-api/openapi-ts

export type ConfigurationEditorItemRequestModel = {
    key?: string | null;
    value?: {
        [key: string]: unknown;
    } | null;
};

export type ConfigurationEditorModel = {
    key: string;
    name: string;
    description?: string | null;
    icon?: string | null;
    group?: string | null;
    fields: Array<(ContentmentConfigurationFieldModel)>;
    defaultValues?: {
        [key: string]: unknown;
    } | null;
    overlaySize: OverlaySize;
    expressions?: {
        [key: string]: (string);
    } | null;
    /**
     * @deprecated
     */
    nameTemplate?: string | null;
    /**
     * @deprecated
     */
    descriptionTemplate?: string | null;
};

export type ConfigurationEditorModelsResponseModel = {
    items: Array<(ConfigurationEditorModel)>;
};

export type ContentmentConfigurationFieldModel = {
    key?: string | null;
    name?: string | null;
    description?: string | null;
    view?: string | null;
    propertyEditorUiAlias?: string | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type DataListConfigurationRequestModel = {
    dataSource?: Array<(ConfigurationEditorItemRequestModel)> | null;
    listEditor?: Array<(ConfigurationEditorItemRequestModel)> | null;
};

export type DataListEditorResponseModel = {
    propertyEditorUiAlias?: string | null;
    config?: Array<(DataTypePropertyPresentationModel)> | null;
};

export type DataListItem = {
    description?: string | null;
    disabled: boolean;
    group?: string | null;
    icon?: string | null;
    name?: string | null;
    value?: string | null;
    [key: string]: (unknown) | undefined;
};

export type DataPickerEditorRequestModel = {
    id: string;
    dataTypeKey: string;
    dataSource?: Array<(ConfigurationEditorItemRequestModel)> | null;
    displayMode?: Array<(ConfigurationEditorItemRequestModel)> | null;
    values?: Array<(string)> | null;
};

export type DataPickerEditorResponseModel = {
    propertyEditorUiAlias?: string | null;
    config?: Array<(DataTypePropertyPresentationModel)> | null;
};

export type DataTypePropertyPresentationModel = {
    alias: string;
    value?: unknown;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type OverlaySize = 'Small' | 'Medium' | 'Large';

export type PagedModelDataListItemModel = {
    items: Array<(DataListItem)>;
    total: number;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: (unknown) | undefined;
};

export type $OpenApiTs = {
    '/umbraco/management/api/v1/contentment/configuration-editor/models': {
        get: {
            req: {
                type?: string;
            };
            res: {
                /**
                 * OK
                 */
                200: ConfigurationEditorModelsResponseModel;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * The authenticated user do not have access to this resource
                 */
                403: unknown;
                /**
                 * Not Found
                 */
                404: ProblemDetails;
            };
        };
    };
    '/umbraco/management/api/v1/contentment/data-list/editor': {
        post: {
            req: {
                requestBody?: DataListConfigurationRequestModel;
            };
            res: {
                /**
                 * OK
                 */
                200: DataListEditorResponseModel;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * The authenticated user do not have access to this resource
                 */
                403: string;
                /**
                 * Not Found
                 */
                404: ProblemDetails;
            };
        };
    };
    '/umbraco/management/api/v1/contentment/data-picker/editor': {
        post: {
            req: {
                requestBody?: DataPickerEditorRequestModel;
            };
            res: {
                /**
                 * OK
                 */
                200: DataPickerEditorResponseModel;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * The authenticated user do not have access to this resource
                 */
                403: string;
                /**
                 * Not Found
                 */
                404: ProblemDetails;
            };
        };
    };
    '/umbraco/management/api/v1/contentment/data-picker/search': {
        get: {
            req: {
                dataTypeKey?: string;
                id?: string;
                pageNumber?: number;
                pageSize?: number;
                query?: string;
            };
            res: {
                /**
                 * OK
                 */
                200: PagedModelDataListItemModel;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * The authenticated user do not have access to this resource
                 */
                403: unknown;
                /**
                 * Not Found
                 */
                404: ProblemDetails;
            };
        };
    };
    '/umbraco/management/api/v1/contentment/data/assemblies': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<(DataListItem)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * The authenticated user do not have access to this resource
                 */
                403: unknown;
                /**
                 * Not Found
                 */
                404: ProblemDetails;
            };
        };
    };
    '/umbraco/management/api/v1/contentment/data/enums': {
        get: {
            req: {
                assembly?: string;
            };
            res: {
                /**
                 * OK
                 */
                200: Array<(DataListItem)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * The authenticated user do not have access to this resource
                 */
                403: unknown;
                /**
                 * Not Found
                 */
                404: ProblemDetails;
            };
        };
    };
};